# Generated by Django 3.2.8 on 2021-11-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('e_mail', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('mobile_phone_number', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
