# Generated by Django 3.2.8 on 2021-11-06 14:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211106_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
