# Generated by Django 3.2.8 on 2021-11-20 08:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_client_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='', upload_to='avatar/photos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Description'),
        ),
    ]
